config/routes.rb
Sudoku::Application.routes.draw do
  root to: 'puzzles#new'

  resources :puzzles do
    collection do
      post 'solve'
    end
  end

end

app/models/puzzle.rb
class Puzzle

  attr_accessor :grid, :error

  def initialize(grid)
    @grid = grid
    @valid = true
    @stuck = false
    @error = nil
  end

  def self.generate

  end

  def solve
    return unless valid_grid?
    solve_squares
    guess if stuck? && valid?
    valid? ? @grid : nil
  end

  private

  def valid_grid?
    valid_grid_size? && valid_grid_values?
  end

  def valid_grid_size?
    if grid.length != 81
      @valid = false
      @error = "Grid is not 9x9"
    end
    valid?
  end

  def valid_grid_values?
    @grid.each_with_index do |value, index|
      unless value == 0
        used_values = values_for_square index
        if used_values.include? value
          @valid = false
          @error = "Grid has conflicting values"
          return false
        end
      end
    end
    true
  end

  def guess
    guess_index = @grid.index(0)
    options = valid_options(guess_index)
    options.each do |guess_value|
      new_grid = @grid.dup
      new_grid[guess_index] = guess_value
      sudoku = Puzzle.new(new_grid)
      if sudoku.solve
        @grid = sudoku.grid
        return
      end
    end
    @valid = false
  end

  def solve_squares
    until solved? || stuck?
      @stuck = true
      @grid.each_with_index do |value, index|
        solve_square(index) if value == 0
        return unless valid?
      end
    end
  end

  def solve_square(index)
    options = valid_options(index)

    @valid = options.length != 0
    if options.length == 1
      @stuck = false
      @grid[index] = options[0]
    end
  end

  def valid_options(index)
    [1,2,3,4,5,6,7,8,9] - values_for_square(index)
  end

  def values_for_square(index)
    column_values(index) + row_values(index) + grid_values(index)
  end

  def column_values(index)
    values = []
    (index % 9).step(80, 9) do |column_index|
      values << @grid[column_index] unless column_index == index || @grid[column_index] == 0
    end
    values
  end

  def row_values(index)
    values = []
    row_index = index - (index % 9)
    9.times {
      values << @grid[row_index] unless row_index == index || @grid[row_index] == 0
      row_index += 1
    }
    values
  end

  def grid_values(index)
    values = []
    row_start = (index / 27) * 3 * 9
    column_start = ((index % 9) / 3) * 3
    grid_start = row_start + column_start
    0.step(18, 9) do |row|
      0.step(2) do |column|
        grid_index = grid_start + row + column
        values << @grid[grid_index] unless grid_index == index || @grid[grid_index] == 0
      end
    end
    values
  end

  def stuck?
    @stuck
  end

  def valid?
    @valid
  end

  def solved?
    !@grid.include?(0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController

  def index
  end

  def solve
    grid = params[:puzzle].map{|i| i.empty? ? 0 : i.to_i}
    @puzzle = Puzzle.new(grid)
    @puzzle.solve
    redirect_to puzzles_path, notice: 'Invalid Puzzle' if @puzzle.invalid?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sudoku" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/puzzles/index.html.erb
<div class="page-header">
  <h1>Sudoku</h1>
</div>
<%= form_tag solve_puzzles_path, method: 'post' %>
  <table class="table table-bordered">
    <% 9.times do |row| %>
      <tr>
        <% 9.times do |col| %>
          <td class="<%= "row-#{row} col-#{col}" %>"><%= number_field_tag 'puzzle[]', nil, in: 0..9, class: 'input-mini' %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <button type="submit" class="btn">Solve</button>
</form>

app/views/puzzles/solve.html.erb
<div class="page-header">
  <h1>Sudoku</h1>
</div>
<table class="table table-bordered">
  <% count = 0 %>
  <% @puzzle.grid.each do |number| %>
    <%= "<tr>".html_safe if count % 9 == 0 %>
      <td class="<%= "row-#{count / 9} col-#{count % 9}" %>"><%= number %></td>
    <%= "</tr>".html_safe if count % 9 == 8 %>
    <% count += 1 %>
  <% end %>
</table>

<%= link_to "Solve Another", new_puzzle_path, class: 'btn' %>